2022-05-06 20:15:05,553 ERROR: Exception on /user/wangwu [GET] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\codeproject\PycharmProjects\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\codeproject\PycharmProjects\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "D:\codeproject\PycharmProjects\microblog\app\templates\base.html", line 54, in block 'content'
    {% block app_content %}{% endblock %}
  File "D:\codeproject\PycharmProjects\microblog\app\templates\user.html", line 22, in block 'app_content'
    {{ form.hidden_tag() }}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-05-06 20:15:47,244 ERROR: Exception on /user/wangwu [GET] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\codeproject\PycharmProjects\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\codeproject\PycharmProjects\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "D:\codeproject\PycharmProjects\microblog\app\templates\base.html", line 54, in block 'content'
    {% block app_content %}{% endblock %}
  File "D:\codeproject\PycharmProjects\microblog\app\templates\user.html", line 22, in block 'app_content'
    {{ form.hidden_tag() }}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-05-06 20:18:31,284 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:43]
2022-05-06 20:18:32,781 ERROR: Exception on /user/wangwu [GET] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\codeproject\PycharmProjects\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\codeproject\PycharmProjects\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "D:\codeproject\PycharmProjects\microblog\app\templates\base.html", line 54, in block 'content'
    {% block app_content %}{% endblock %}
  File "D:\codeproject\PycharmProjects\microblog\app\templates\user.html", line 17, in block 'app_content'
    {{ form.hidden_tag() }}
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-05-06 20:19:10,812 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:43]
